# roles/package_installer/tasks/main.yml
---
- name: Install packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ packages }}"
  when: ansible_os_family == "Debian"

- name: Install packages
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  loop: "{{ packages }}"
  when: ansible_os_family == "RedHat"