---
- hosts: all
  vars:
    desktop_extra:
      - inkscape
      - gimp
      - libreoffice

      - redshift
      - timeshift

  tasks:
    - name: Install packages
      become: yes
      apt:
        name: "{{ desktop_extra }}"
        state: present
- import_playbook: playbooks/veracrypt.yml
...