---
- hosts: all
  vars:
    desktop_extra:
      - inkscape
      - gimp
      - libreoffice

  tasks:
    - name: Install packages
      become: yes
      apt:
        name: "{{ desktop_extra }}"
        state: present
...