---
- hosts: all
  vars:
    desktop:
      - python3
      - python3-venv
      - python3-pip

      - curl

      - i3
      - i3status
      - i3lock
      - picom
      - arandr
      - jq

      - feh

      - dmenu
      - rofi

      - redshift

      - timeshift

      - ximput
      - flameshot
      - alacritty

      - chromium
      - firefox

  roles:
    - role: package_installer
      vars:
        packages: "{{ dev }}"

  tasks: 
    - name: Install Thunar with all reccommended packages
      become: yes
      apt:
        name: thunar
        state: present
        install_recommends: yes

    - include_tasks: playbooks/vscode.yml
    - include_tasks: playbooks/discord.yml
    - include_tasks: playbooks/dotfiles.yml

...
