---
- hosts: all
  vars:
    desktop:
      - pulseaudio-utils

      - python3
      - python3-venv
      - python3-pip

      - stow
      - curl

      - i3
      - i3status
      - i3lock
      - python3-i3ipc
      - picom
      - arandr
      - jq

      - feh

      - dmenu
      - rofi

      - redshift

      - timeshift

      - flameshot
      - kitty

      #- chromium-browser
      #- firefox

  tasks: 
    - name: Install packages
      become: yes
      apt:
        name: "{{ desktop }}"
        state: present

    - name: Install Thunar with all reccommended packages
      become: yes
      apt:
        name: thunar
        state: present
        install_recommends: yes

    - name: Set Thunar as default file manager
      become: yes
      command: xdg-mime default thunar.desktop inode/directory

    - name: Install fonts
      become: yes
      shell: chmod +x ./scripts/* && ./scripts/install_fonts.sh

- import_playbook: playbooks/dotfiles.yml
- import_playbook: playbooks/brave.yml
- import_playbook: playbooks/veracrypt.yml
- import_playbook: playbooks/vscode.yml
- import_playbook: playbooks/discord.yml

...
