---
- hosts: all
  vars:
    desktop:
      - python3
      - python3-venv
      - python3-pip

      - curl

      - i3
      - i3status
      - i3lock
      - python3-i3ipc
      - python3-autotiling
      - picom
      - arandr
      - jq

      - feh

      - dmenu
      - rofi

      - redshift

      - timeshift

      - flameshot
      - alacritty

      - chromium
      #- firefox # Not in repo

  roles:
    - role: package_installer
      vars:
        packages: "{{ desktop }}"

  tasks: 
    - name: Install Thunar with all reccommended packages
      become: yes
      apt:
        name: thunar
        state: present
        install_recommends: yes

- import_playbook: playbooks/brave.yml
- import_playbook: playbooks/vscode.yml
- import_playbook: playbooks/discord.yml
- import_playbook: playbooks/dotfiles.yml

...
