---
- hosts: all
  vars:
    desktop:
      - pulseaudio-utils

      - python3
      - python3-venv
      - python3-pip

      - stow
      - curl

      - i3
      - i3status
      - i3lock
      - python3-i3ipc
      - picom
      - arandr
      - jq
      - xclip
      
      # For mouse sensitivity settings in dotfiles
      - xinput

      # Manage GTK Themes
      - lxappearance      
      - feh

      - dmenu
      - rofi


      - flameshot

  tasks: 
    - name: Install packages
      become: yes
      apt:
        name: "{{ desktop }}"
        state: present

    - name: Install Thunar with all reccommended packages
      become: yes
      apt:
        name: thunar
        state: present
        install_recommends: yes

    - name: Set Thunar as default file manager
      become: yes
      command: xdg-mime default thunar.desktop inode/directory


- import_playbook: playbooks/dotfiles.yml
- import_playbook: playbooks/brave.yml
- import_playbook: playbooks/wezterm.yml
- import_playbook: playbooks/vscode.yml
- import_playbook: playbooks/fonts.yml

...
