---
- hosts: all
  vars:
    desktop:
      - pulseaudio-utils

      - python3
      - python3-venv
      - python3-pip

      - curl

      - i3
      - i3status
      - i3lock
      - python3-i3ipc
      - picom
      - arandr
      - jq

      - feh

      - dmenu
      - rofi

      - redshift

      - timeshift

      - flameshot
      - alacritty

      - chromium-browser
      - firefox

  tasks: 
    - name: Install packages
      become: yes
      apt:
        name: "{{ desktop }}"
        state: present

    - name: Install Thunar with all reccommended packages
      become: yes
      apt:
        name: thunar
        state: present
        install_recommends: yes

- import_playbook: playbooks/brave.yml
- import_playbook: playbooks/veracrypt.yml
- import_playbook: playbooks/vscode.yml
- import_playbook: playbooks/discord.yml
- import_playbook: playbooks/dotfiles.yml

...
