---
- hosts: all
  vars:
    dev:
      # QEMU/KVM/Virt-Manager 
      - qemu-kvm
      - libvirt-daemon-system
      - libvirt-clients
      - bridge-utils
      - virt-manager

      # Reports
      - texlive-latex-recommended
      - texlive-fonts-extra
      - texlive-latex-extra 
      - pandoc
      - p7zip-full


  tasks:
    - name: Install packages
      become: yes
      apt:
        name: "{{ dev }}"
        state: present


#- import_playbook: playbooks/vscode.yml    
- import_playbook: dev_minimal.yml
...