---
- hosts: all
  vars:
    dev:
      # Editors
      - vim
      
      # Version Control
      - git

      # Interpreters, compilers, runtimes, etc...
      - gcc

      - python3
      - python3-pip
      - python3-venv

      #- nodejs
      - npm
      
      # Build tools
      - make
      - cmake

      # Debugging
      - gdb

      # Environment / workflow
      - tmux

      # Containerization
      - docker.io
      - docker-compose

      # Virtualization
      
      # TODO: Not in default repos (maybe better for desktop_extra.yml)
      #- virtualbox

      # QEMU/KVM/Virt-Manager 
      - qemu-kvm
      - libvirt-daemon-system
      - libvirt-clients
      - bridge-utils
      - virt-manager

      # Reports
      - texlive-latex-recommended
      - texlive-fonts-extra
      - texlive-latex-extra 
      - pandoc
      - p7zip-full


  tasks:
    - name: Install packages
      become: yes
      apt:
        name: "{{ dev }}"
        state: present


#- import_playbook: playbooks/vscode.yml    
...