---
- hosts: all
  vars:
    dev_minimal:
      # Editors
      - vim
      
      # Version Control
      - git

      # Interpreters, compilers, runtimes, etc...
      - gcc

      - python3
      - python3-pip
      - python3-venv

      #- nodejs
      - npm
      
      # Build tools
      - make
      - cmake

      # Debugging
      - gdb

      # Containerization
      - docker.io

      # Virtualization
      
      # TODO: Not in default repos (maybe better for desktop_extra.yml)
      #- virtualbox


  tasks:
    - name: Install packages
      become: yes
      apt:
        name: "{{ dev_minimal }}"
        state: present


...