---
- hosts: all
  name: Install my dotfiles.
  vars:
    dotfiles_repo: https://github.com/Cam-Can-Do/dotfiles
    dotfiles_dir: "{{ ansible_env.HOME }}/dotfiles_repo"
  tasks:
    - name: Clone dotfiles repository
      git:
        repo: "{{ dotfiles_repo }}"
        dest: "{{ dotfiles_dir }}"

    - name: Ensure ~/.config directory exists
      file:
        path: "{{ ansible_env.HOME }}/.config"
        state: directory

    - name: Ensure rsync is installed
      package:
        name: rsync
        state: present

    - name: Copy dotfiles to ~/.config
      command: /usr/bin/rsync -a --delete "{{ item.src }}/" "{{ item.dest }}/"
      with_items: "{{ lookup('fileglob', dotfiles_dir + '/*', wantlist=True) | map('basename') | list }}"
      vars:
        src: "{{ dotfiles_dir }}/{{ item }}"
        dest: "{{ ansible_env.HOME }}/.config/{{ item }}"
