---
- hosts: all
  name: Install my dotfiles.
  vars:
    dotfiles_repo: https://github.com/Cam-Can-Do/dotfiles
    dotfiles_dir: "./dotfiles_repo"
  tasks:
    - name: Clone dotfiles repository
      git:
        repo: "{{ dotfiles_repo }}"
        dest: "{{ dotfiles_dir }}"

    - name: Ensure ~/.config directory exists
      file:
        path: "{{ ansible_env.HOME }}/.config"
        state: directory

    - name: Copy dotfiles to ~/.config
      command: >
        /usr/bin/rsync -a --delete "{{ item.src }}/" "{{ item.dest }}/"
      with_items: >
        {{ lookup('fileglob', dotfiles_dir + '/*', wantlist=True) | map('basename') | list }}
      loop_control:
        loop_var: item
      vars:
        items: >
          {{ lookup('fileglob', dotfiles_dir + '/*', wantlist=True) | map('basename') | list }}
        item:
          src: "{{ dotfiles_dir }}/{{ item }}"
          dest: "~/.config/{{ item }}"
