---
- hosts: all
  vars: 
    general:
      - libreoffice

      - curl
      - wget
      - unzip
      - zip
      - jq
      - tree
      - htop
      - net-tools
      - iputils-ping
      - dnsutils
      - clamav

      - fonts-noto

  roles:
    - role: package_installer
      vars:
        packages: "{{ general }}"
...