---
- hosts: all
  vars: 
    general:
      - curl
      - wget
      - unzip
      - zip
      - jq
      - tree
      - htop
      - net-tools
      - iputils-ping
      - dnsutils
      - clamav
      - neofetch

      - fonts-noto

  tasks:
    - name: Install packages
      become: yes
      apt:
        name: "{{ general }}"
        state: present
...