---
- hosts: all
  vars: 
    general:
      - libreoffice

      - curl
      - wget
      - unzip
      - zip
      - jq
      - tree
      - htop
      - net-tools
      - iputils-ping
      - dnsutils
      - clamav

      - noto-fonts
      - noto-fonts-emoji
      - noto-fonts-cjk
      - noto-fonts-extra

  roles:
    - role: package_installer
      vars:
        packages: "{{ general }}"
...