---
- hosts: all
  vars:
    dev:
      # Editors
      - vim
      
      # Version Control
      - git

      # Interpreters, compilers, runtimes, etc...
      - gcc

      - python3
      - python3-pip
      - python3-venv

      - nodejs
      - npm
      
      # Build tools
      - make
      - cmake

      # Debugging
      - gdb

      # Environment / workflow
      - tmux

      # Containerization
      - docker
      - docker-compose

      # Virtualization
      - virtualbox

      - qemu-kvm
      - libvirt-daemon-system
      - libvirt-clients
      - bridge-utils
      - virt-manager


  roles:
    - role: package_installer
      vars:
        packages: "{{ dev }}"

  tasks:
    - name: Add user to libvirt group
      become: yes
      user:
        name: "{{ ansible_user }}"
        groups: libvirt
        append: yes 

    - name: Check if VSCode is installed
      command: dpkg -s code
      register: vscode_check
      failed_when: vscode_check.rc not in [0, 1]
      changed_when: false
    
    - name: Install VSCode
      block:
        - name: Download VSCode .deb package
          get_url:
            url: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64
            dest: /tmp/code.deb
            mode: '0644'
        
        - name: Install VSCode
          apt:
            deb: /tmp/code.deb
      when: vscode_check.rc == 1
      become: yes
...