---
- hosts: localhost
  vars:
    appimage_dir: "/opt/appimages"

    appimages:
      - name: logseq
        url: "https://github.com/logseq/logseq/releases/download/0.10.9/Logseq-linux-x64-0.10.9.AppImage"
  tasks:
    - name: Ensure AppImage directory exists
      file:
        path: "{{ appimage_dir }}"
        state: directory

    - name: Ensure AppImage directory is in PATH
      lineinfile:
        path: "~/.bashrc"
        line: "export PATH=$PATH:{{ appimage_dir }}"
      register: path

    - name: Download and install AppImages
      block:
        - name: Check if AppImage is already downloaded
          stat:
            path: "{{ appimage_dir }}/{{ item.name }}"
          register: appimage

        - name: Download AppImage
          get_url:
            url: "{{ item.url }}"
            dest: "{{ appimage_dir }}/{{ item.name }}"
            mode: '0755'
          when: not appimage.stat.exists
      loop: "{{ appimages }}"