---
- hosts: all
  tasks:
    - name: Check if Brave Browser is installed
      command: dpkg -s brave-browser
      register: brave_check
      failed_when: brave_check.rc not in [0, 1]
      changed_when: false

    - name: Install Brave Browser
      block:
        - name: Download Brave Browser GPG key
          get_url:
            url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
            dest: /usr/share/keyrings/brave-browser-archive-keyring.gpg
            mode: '0644'

        - name: Add Brave Browser repository
          apt_repository:
            repo: deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main
            state: present
            update_cache: yes

        - name: Install Brave Browser
          apt:
            name: brave-browser
            state: present
      when: brave_check.rc == 1
      become: yes
