---
- hosts: all
  name: Install my dotfiles.
  vars:
    dotfiles_repo: "https://github.com/Cam-Can-Do/dotfiles"
    dotfiles_dir: "~/dotfiles"
  tasks:
    - name: Clone dotfiles repository
      shell: |
        git clone {{ dotfiles_repo }} {{ dotfiles_dir }}
        cd {{ dotfiles_dir }}
        stow .