---
- name: Clone a GitHub repository and copy contents to ~/.config
  hosts: localhost
  gather_facts: yes
  tasks:
    - name: Install git if not present
      apt:
        name: git
        state: present
      become: yes

    - name: Ensure the ~/.config directory exists
      file:
        path: "{{ ansible_env.HOME }}/.config"
        state: directory
        mode: '0755'

    - name: Clone the GitHub repository
      git:
        repo: 'https://github.com/Cam-Can-Do/dotfiles.git'
        #repo: 'https://github.com/typecraft-dev/dotfiles.git'

        dest: '/tmp/cloned-repo'

    - name: Copy the contents to ~/.config
      command: >
        rsync -av --delete /tmp/cloned-repo/ {{ ansible_env.HOME }}/.config/

    - name: Clean up the temporary repository
      file:
        path: '/tmp/cloned-repo'
        state: absent
