---
- hosts: all
  name: Install my dotfiles.
  vars:
    dotfiles_repo: https://github.com/Cam-Can-Do/dotfiles
    dotfiles_dir: "./dotfiles_repo"
  tasks:
    - name: Clone dotfiles repository
      git:
        repo: "{{ dotfiles_repo }}"
        dest: "{{ dotfiles_dir }}"

    - name: Ensure ~/.config directory exists
      file:
        path: "~/.config"
        state: directory

    - name: Find files and directories in dotfiles_dir
      find:
        paths: "{{ dotfiles_dir }}"
        file_type: any
      register: dotfiles

    - name: Synchronize dotfiles to ~/.config
      synchronize:
        src: "{{ item.path }}"
        dest: "~/.config"
        delete: yes
        recursive: yes
      loop: "{{ dotfiles.files }}"

- import_playbook: setup_i3_scripts.yml