---
- hosts: all
  name: Install my dotfiles.
  vars:
    dotfiles_repo: "https://github.com/Cam-Can-Do/dotfiles"
    dotfiles_dir: "~/dotfiles"
  tasks:
    - name: Clone dotfiles repository
      shell: |
        git clone {{ dotfiles_repo }} {{ dotfiles_dir }}

    - name: Ensure GNU Stow installed
      become: yes
      apt:
        name: stow
        state: present

    - name: Stow dotfiles (overwrites conflicting files)
      shell: |
        cd {{ dotfiles_dir }}
        stow . --adopt
