# source: https://waylonwalker.com/ansible-install-fonts/
---
- hosts: all
  name: Install fonts
  tasks:
    - name: ensure fonts directory
      file:
        path: "{{ lookup('env', 'HOME') }}/.fonts"
        state: directory

    - name: Hack exists
      shell: "find {{ lookup('env', 'HOME') }}/.fonts -iname 'Hack*Nerd*Font*Complete*' -type f"
      register: hack_exists
      ignore_errors: yes

    - name: Download Hack
      when: hack_exists is failed
      ansible.builtin.unarchive:
        src: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/Hack.zip
        dest: "{{ lookup('env', 'HOME') }}/.fonts/"
        remote_src: yes

    - name: Refresh font cache to enable new font(s)
      shell: "fc-cache -fv"
