---
- hosts: all
  tasks:
    - name: Check if VeraCrypt is installed
      command: dpkg -s veracrypt
      register: veracrypt_check
      failed_when: veracrypt_check.rc not in [0, 1]
      changed_when: false

    - name: End play if VeraCrypt is already installed
      meta: end_play
      when: veracrypt_check.rc == 0

    - name: Download VeraCrypt .deb package
      get_url:
        url: "https://launchpad.net/veracrypt/trunk/1.26.7/+download/veracrypt-1.26.7-Debian-12-amd64.deb"
        dest: "/tmp/veracrypt.deb"

    - name: Download VeraCrypt PGP signature
      get_url:
        url: "https://launchpad.net/veracrypt/trunk/1.26.7/+download/veracrypt-1.26.7-Debian-12-amd64.deb.sig"
        dest: "/tmp/veracrypt.deb.sig"

    - name: Download VeraCrypt public key
      get_url:
        url: "https://www.idrix.fr/VeraCrypt/VeraCrypt_PGP_public_key.asc"
        dest: "/tmp/veracrypt_public_key.asc"

    - name: Import VeraCrypt public key
      shell: gpg --import /tmp/veracrypt_public_key.asc

    - name: Verify PGP signature
      shell: gpg --verify /tmp/veracrypt.deb.sig /tmp/veracrypt.deb
      ignore_errors: yes
      register: gpg_verify
      failed_when: "'Good signature' not in gpg_verify.stdout"

    - name: Download SHA512 sum file
      get_url:
        url: "https://launchpadlibrarian.net/730970179/veracrypt-1.26.7-sha512sum.txt"
        dest: "/tmp/veracrypt.sha512sum.txt"


    - name: Verify SHA512 sum
      shell: echo "{{ veracrypt_sha512.stdout }}  /tmp/veracrypt.deb" | sha512sum -c -
      ignore_errors: yes
      register: sha512_check
      failed_when: "'OK' not in sha512_check.stdout"

    - name: Install VeraCrypt
      command: dpkg -i /tmp/veracrypt.deb