---
- hosts: localhost
  tasks:
    - name: Ensure python3-venv is installed
      apt:
        name: python3-venv
        state: present
      become: yes

    - name: Ensure the i3 scripts directory exists
      file:
        path: "../venv/i3_scripts"
        state: directory

    - name: Create a virtual environment
      command:
        cmd: python3 -m venv ../venv/i3_scripts
        creates: ../venv/i3_scripts

    - name: Check if virtual environment exists
      stat:
        path: ../venv/i3_scripts
      register: venv

    - name: Install packages
      command:
        cmd: ../venv/i3_scripts/bin/pip install i3ipc
      when: venv.stat.exists
      
    - name: Ensure ~/.config/i3 directory exists
      file:
        path: "~/.config/i3"
        state: directory

    - name: Ensure scripts are executable
      file:
        path: "~/.config/i3/scripts"
        mode: u+x
        state: directory
        recurse: yes