---
- hosts: all
  tasks:
    - name: Check if VSCode is installed
      command: dpkg -s code
      register: vscode_check
      failed_when: vscode_check.rc not in [0, 1]
      changed_when: false

    - name: End play if already installed
      meta: end_play
      when: vscode_check.rc == 0

    - name: Fetch JSON object
      uri:
        url: https://code.visualstudio.com/sha?build=stable
        return_content: yes
      register: vscode_json

    - name: Extract SHA256 checksum for linux-deb-x64
      set_fact:
        vscode_sha256: "{{ vscode_json.content | from_json | json_query('products[?platform.os==`linux-deb-x64`].sha256hash | [0]') }}"

    - name: Print Server's SHA256 checksum
      debug:
        msg: "SHA256: {{ vscode_sha256 }}"

    - name: Download VSCode .deb package
      get_url:
        url: "https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64"
        dest: "/tmp/code.deb"
        checksum: "sha256:{{ vscode_sha256 }}"

    - name: Calculate checksum of downloaded file
      command: sha256sum /tmp/code.deb
      register: calculated_checksum
      changed_when: false

    - name: Print calculated checksum
      debug:
        msg: "Calculated checksum: {{ calculated_checksum.stdout.split()[0] }}"

    - name: Install VSCode
      become: yes
      apt:
        deb: "/tmp/code.deb"